juan_store/carts/urls.py
from django.urls import path
from . import views
app_name="carts"

urlpatterns = [
    path("", views.cart, name="cart"),
    path("agregar", views.add, name="add"),
    path("eliminar", views.remove, name="remove")
]

juan_store/juan_store/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings
from . import views

from productos.views import ProductoListView

urlpatterns = [#registrar las vistas 
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path("", ProductoListView.as_view(), name="index"),
    path("usuarios/login", views.login_view, name="login"),
    path("usuarios/registro", views.registro, name="registro"),
    path("usuarios/logout", views.logout_view, name="logout"),
    path('admin/', admin.site.urls),
    path("productos/", include("productos.urls")),
    path("carrito/", include("carts.urls")),
    path("orden/", include("orders.urls")),
    path("direcciones/", include("shipping_addresess.urls")),
    path("codigos/", include("promo_codes.urls")),
    path("pagos/", include("billing_profiles.urls")),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

juan_store/productos/urls.py
from django.urls import path
from . import views


app_name= "productos"

urlpatterns = [#registrar las vistas 
    path("search",views.ProductoSearchListView.as_view(),name="search"),
    path("<slug:slug>",views.ProductoDetailView.as_view(), name="producto") #<nombre_atributo:tipo_atributo>
    
]

juan_store/productos/models.py
import uuid

from django.db import models
from django.utils.text import slugify

from django.db.models.signals import pre_save

class Producto(models.Model):
    titulo = models.CharField(max_length=50)
    descripcion = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    slug = models.SlugField(null=False, blank=False, unique=True)
    imagen = models.ImageField(upload_to="productos/", null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    #def save(self, *args, **kwargs):
     #   self.slug = slugify(self.titulo)
      #  super(Producto, self).save(*args, **kwargs)
    def __str__(self):
        return self.titulo
def set_slug(sender, instance, *args, **kwargs):
    if instance.titulo and not instance.slug:
        slug = instance.slug = slugify(instance.titulo)
        while Producto.objects.filter(slug=slug).exists():
            slug= slugify(
                "{%s}-%s" %(instance.titulo,str(uuid.uuid4())[:8])
            )
        instance.slug = slug
pre_save.connect(set_slug,sender=Producto)

juan_store/productos/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from django.db.models import Q
from .models import Producto
# Create your views here.
class ProductoListView(ListView):
    template_name = "index.html"
    queryset = Producto.objects.all().order_by("-id")
    paginate_by = 1

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["mesage"] = "Listado de productos"
        return context

class ProductoDetailView(DetailView):
    model = Producto
    template_name = "productos/producto.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        return context

class ProductoSearchListView(ListView):
    template_name = "productos/search.html"
    
    def get_queryset(self):
        #filters = Q(titulo__icontains=self.query() | Q(category__titulo__icontains=self.query()))
        filters = Q(categoria__titulo__icontains=self.query()) |Q(titulo__icontains=self.query())
        return Producto.objects.filter(filters)

    def query(self):
        return self.request.GET.get("q")
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.query()
        context["count"] = context["producto_list"].count()
        return context

juan_store/productos/templates/productos/snippets/list.html
<div class="row">
    {% for itera in producto_list %}
        <div class="col-3 mt-5">
            {%include 'productos/snippets/productos.html' with producto=itera%}
        </div> 
    {% endfor %}
</div>

juan_store/productos/templates/productos/snippets/productos.html
<div class="card h-100">
    {%if producto.imagen%}
        <img src="{{producto.imagen.url}}" alt="imagen producto" height="200">
    {%endif%}
    
    <div class="card-body">
        <h5 class="card-title"> {{producto.titulo}}</h5>
        <p class="card-text"> {{producto.descripcion}}</p>
        <a href="{% url 'productos:producto' producto.slug%}" class="btn btn-primary">ver mas</a>
    </div>
</div>

juan_store/productos/templates/productos/snippets/search.html
<form action="{% url 'productos:search'%}">
    <div class="input-group">
        <input type="text" name="q" value="{{query}}" class="form-control" placeholder="Buscar">
        <div class="input-group-append">
            <input type="submit" name="" value="Buscar" class="btn btn-primary">
        </div>
    </div>
</form>