juan_store/carts/urls.py
from django.urls import path
from . import views
app_name="carts"

urlpatterns = [
    path("", views.cart, name="cart"),
    path("agregar", views.add, name="add"),
    path("eliminar", views.remove, name="remove")
]

juan_store/juan_store/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings
from . import views

from productos.views import ProductoListView

urlpatterns = [#registrar las vistas 
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path("", ProductoListView.as_view(), name="index"),
    path("usuarios/login", views.login_view, name="login"),
    path("usuarios/registro", views.registro, name="registro"),
    path("usuarios/logout", views.logout_view, name="logout"),
    path('admin/', admin.site.urls),
    path("productos/", include("productos.urls")),
    path("carrito/", include("carts.urls")),
    path("orden/", include("orders.urls")),
    path("direcciones/", include("shipping_addresess.urls")),
    path("codigos/", include("promo_codes.urls")),
    path("pagos/", include("billing_profiles.urls")),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

juan_store/carts/models.py
import uuid,decimal
from django.db import models

from users.models import User
from productos.models import Producto
from orders.common import OrderStatus

from django.db.models.signals import pre_save, m2m_changed, post_save

# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Producto, through='CartProductos')
    subtotal = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    FEE = 0.05

    def __str__(self):
        return self.cart_id

    def update_totals(self):
        self.update_subtotal()
        self.update_total()

        if self.order:
            self.order.update_total()
    
    def update_subtotal(self):
        self.subtotal = sum([
            cp.quantity * cp.producto.price for cp in self.productos_related()
        ])
        self.save()

    def update_total(self):
        self.total = self.subtotal + (self.subtotal * decimal.Decimal(Cart.FEE))
        self.save()
        
    def productos_related(self):
        return self.cartproductos_set.select_related('producto')
    
    def has_products(self):
        return self.productos.exists()


    @property
    def order(self):
        return self.order_set.filter(status=OrderStatus.CREATED).first()

class CartProductosManager(models.Manager):
    def create_or_update_quantity(self, cart, producto, quantity=1):
        object, created = self.get_or_create(cart=cart, producto=producto)

        if not created:
            quantity = object.quantity + quantity
        object.update_quantity(quantity)
        return object


class CartProductos(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = CartProductosManager()
    def update_quantity(self, quantity=1):
        self.quantity = quantity
        self.save()

#callback
def set_cart_id(sender, instance, *args, **kwargs):
    if not instance.cart_id:
        instance.cart_id = str(uuid.uuid4())

def update_totals(sender, instance, action, *args, **kwargs ):
    if action == "post_add" or action == "post_remove" or action == "post_clear":
        instance.update_totals()

def post_save_update_totals(sender, instance, *args, **kwargs):
    instance.cart.update_totals()

pre_save.connect(set_cart_id, sender=Cart)
post_save.connect(post_save_update_totals, sender=CartProductos)
m2m_changed.connect(update_totals, sender=Cart.productos.through)

juan_store/carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .utils import get_or_create_cart
from productos.models import Producto
from .models import CartProductos

# Create your views here.

def cart(request):
    #request.session["cart_id"] = None
    cart = get_or_create_cart(request)

    #crear una session
    #request.session["cart_id"]= "123"#diccionario

    #obtendremos el valor de una session
    #valor = request.session.get("cart_id")
    #print(valor)
    #eliminar una session
    #request.session["cart_id"] = None
    return render(request, "carts/cart.html", {
        "cart":cart
    })

def add(request):
    cart = get_or_create_cart(request)
    producto = get_object_or_404(Producto, pk=request.POST.get("product_id"))#asegurar que muestre el error 404 quiere decir que no es usado un recurso
    quantity = int(request.POST.get("quantity", 1)) #por el servidor recibe por name del formulario
    #producto = Producto.objects.get(pk=request.POST.get("product_id"))

    #cart.productos.add(producto, through_defaults={ 
     #   'quantity': quantity
    #})#aprovechando la relacion agregamos un objecto a esta misma
    cart_producto = CartProductos.objects.create_or_update_quantity(cart=cart, producto=producto, quantity=quantity)

    return render(request, "carts/add.html", {
        'quantity': quantity,
        'cart_producto' : cart_producto,
        "producto" : producto
    })

def remove(request):
    cart = get_or_create_cart(request)
    #asegurar que muestre el error 404 quiere decir que no es usado un recurso
    producto = get_object_or_404(Producto, pk=request.POST.get("product_id"))
    cart.productos.remove(producto)

    return redirect("carts:cart")

juan_store/carts/templates/carts/snippets/add.html
<!-- el action apunta a nuestra vista -->
<form action="{% url 'carts:add' %}" method="post">
    {% csrf_token %} 
    <!-- name= reconoce el valor en la vista ya que se envia al servidor-->
    <input type="hidden" name="product_id" value="{{ producto.id}}">
    <div class="">
        <button type="button" class="btn btn-info d-inline" id="remove">-</button>
        <input type="number" value="1" class="form-control col-sm-1 d-inline" id="quantity" name="quantity" readonly ><!-- readonly es para solo lectura -->
        <button type="button" class="btn btn-info" id="add">+</button>
    </div>
    <div class="mt-2">
        <button type="submit" class="btn btn-warning"> Agregar carrito </button>
    </div>
</form>

<script>
    const add = document.getElementById("add")
    const remove = document.getElementById("remove")
    const quantity = document.getElementById("quantity")

    add.addEventListener('click', function(){
        quantity.value = parseInt(quantity.value) + 1
    })
    remove.addEventListener('click', function(){
        value = parseInt(quantity.value)
        if(value != 1){
            value= value - 1
        }
        quantity.value = value
    })
</script>

juan_store/carts/templates/carts/snippets/remove.html
<form action="{% url 'carts:remove' %}" method="post">
    {% csrf_token %} 
    <input type="hidden" name="product_id" value="{{ producto.id}}">
    <button type="submit" class="btn btn-link text-danger" style="padding: 0px;"> Eliminar </button>
</form>