juan_store/carts/urls.py
from django.urls import path
from . import views
app_name="carts"

urlpatterns = [
    path("", views.cart, name="cart"),
    path("agregar", views.add, name="add"),
    path("eliminar", views.remove, name="remove")
]

juan_store/juan_store/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings
from . import views

from productos.views import ProductoListView

urlpatterns = [#registrar las vistas 
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path("", ProductoListView.as_view(), name="index"),
    path("usuarios/login", views.login_view, name="login"),
    path("usuarios/registro", views.registro, name="registro"),
    path("usuarios/logout", views.logout_view, name="logout"),
    path('admin/', admin.site.urls),
    path("productos/", include("productos.urls")),
    path("carrito/", include("carts.urls")),
    path("orden/", include("orders.urls")),
    path("direcciones/", include("shipping_addresess.urls")),
    path("codigos/", include("promo_codes.urls")),
    path("pagos/", include("billing_profiles.urls")),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

juan_store/orders/urls.py
from django.urls import path

from . import views

app_name= "orders"

urlpatterns= [
    path("", views.order, name="order"),
    path("direccion", views.address, name="address"),
    path("seleccionar/direccion", views.select_address, name="select_address"),
    path("establecer/direccion/<int:pk>", views.check_address, name="check_address"),
    path("confirmacion", views.confirm, name="confirm"),
    path("cancelar", views.cancel, name="cancel"),
    path("completar", views.complete, name="complete"),
    path("pago", views.payment, name="payment"),
    path("completados", views.OrderListView.as_view(), name="completeds"),
]

juan_store/promo_codes/urls.py
from django.urls import path

from . import views

app_name = "promo_codes"

urlpatterns=[
    path("validar", views.validate, name="validate")
]

juan_store/shipping_addresess/urls.py
from django.urls import path

from . import views

app_name = "shipping_addresses"

urlpatterns =[
    path("", views.shippingAddressListView.as_view(), name="shipping_addresses"),
    path("nuevo", views.create, name="create"),
    path("editar/<int:pk>", views.shippingAddressUpdateView.as_view(), name="update"),
    path("eliminar/<int:pk>", views.shippingAddressDeleteView.as_view(), name="delete"),
    path("default/<int:pk>", views.default, name="default"),
]

juan_store/orders/models.py
import uuid
import decimal
from enum import Enum
from django.db import models
from django.db.models.signals import pre_save

from users.models import User
from carts.models import Cart
from promo_codes.models import PromoCode
from shipping_addresess.models import ShippingAddress
from billing_profiles.models import BillingProfile
from orders.common import choices, OrderStatus
# Create your models here.

class Order(models.Model):
    order_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, choices=choices, default=OrderStatus.CREATED)
    shipping_total = models.DecimalField(default=5, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    shipping_address = models.ForeignKey(ShippingAddress, null=True, blank=True, on_delete=models.CASCADE)
    promo_code = models.OneToOneField(PromoCode, null=True, blank=True, on_delete=models.CASCADE)

    billing_profile = models.ForeignKey(BillingProfile, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.order_id

    def apply_promo_code(self, promo_code):
        if self.promo_code is None:
            self.promo_code = promo_code
            self.save()

        self.update_total()
        promo_code.use()

    def get_or_set_billing_profile(self):
        if self.billing_profile:
            return self.billing_profile

        billing_profile = self.user.billing_profile

        if billing_profile:
            self.update_billing_profile(billing_profile)

        return billing_profile

    def get_or_set_shipping_address(self):
        if self.shipping_address:
            return self.shipping_address

        shipping_address = self.user.shipping_address

        if shipping_address:
            self.update_shipping_address(shipping_address)

        return shipping_address

    def update_billing_profile(self, billing_profile):
        self.billing_profile = billing_profile
        self.save()


    def update_shipping_address(self, shipping_address):
        self.shipping_address = shipping_address
        self.save()

    def cancel(self):
        self.status = OrderStatus.CANCELED
        self.save()

    def complete(self):
        self.status = OrderStatus.COMPLETED
        self.save()

    def update_total(self):
        self.total = self.get_total()
        self.save()

    def get_discount(self):
        if self.promo_code:
            return self.promo_code.discount
        return 0
   
    def get_total(self):
        return self.cart.total + self.shipping_total - decimal.Decimal(self.get_discount())
    
    def description(self):
        return "compra por ({}) productos".format(self.cart.productos.count())

#callback
def set_order_id(sender, instance, *args, **kwars):
    if not instance.order_id:
        instance.order_id = str(uuid.uuid4())

def set_total(sender, instance, *args, **kwars):
    instance.total = instance.get_total()
#signal antes de almacenar
pre_save.connect(set_order_id, sender=Order)
pre_save.connect(set_total, sender=Order)

juan_store/orders/views.py
import threading #para poner en segundo plano

from django.shortcuts import render, redirect, get_object_or_404

from django.contrib import messages
from django.contrib.auth.decorators import login_required #funciona para redireccionar cuando un usuario no esta auntenticado
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic.list import ListView

from django.db.models.query import EmptyQuerySet

from .models import Order
from shipping_addresess.models import ShippingAddress
from charges.models import Charge
from carts.utils import get_or_create_cart, destroy_cart
from .utils import get_or_create_order, breadcrumb, destroy_order

#decoradores
from .decorators import validate_cart_and_order

#correo
from .mails import Mail
# Create your views here.
#le dice a django que debe estar autenticado LoginRequiredMixin
class OrderListView(LoginRequiredMixin, ListView):
    login_url = "login"
    template_name = "orders/orders.html"

    def get_queryset(self):
        return self.request.user.orders_completed()

#le dice a django que el usuario debe estar autenticado y si no lo redirecciona a la direccion del parametro
@login_required(login_url="login")
@validate_cart_and_order
def order(request, cart, order):
    if not cart.has_products():
        return redirect("carts:cart")
    return render(request, 'orders/order.html', {
        "cart": cart,
        'order' : order,
        "breadcrumb": breadcrumb(),
    })

@login_required(login_url="login")
@validate_cart_and_order
def address(request, cart, order):

    if not cart.has_products():
        return redirect("carts:cart")

    shipping_address = order.get_or_set_shipping_address()
    can_choose_address = request.user.has_shipping_addresses()

    return render(request, "orders/address.html",{
        "cart": cart,
        "order": order,
        "shipping_addresses":shipping_address, 
        "breadcrumb":breadcrumb(address=True),
        "can_choose_address" : can_choose_address,
    })

@login_required(login_url="login")
def select_address(request):
    shipping_addresses = request.user.addresses
    return render(request, "orders/select_address.html",{
        "breadcrumb": breadcrumb(address=True),
        "shipping_addresses": shipping_addresses,

    })

@login_required(login_url="login")
@validate_cart_and_order
def check_address(request, cart, order, pk):
    shipping_address = get_object_or_404(ShippingAddress, pk=pk)

    if request.user.id != shipping_address.user_id:
        return redirect("carts:cart")

    order.update_shipping_address(shipping_address)
    return redirect("orders:address")

@login_required(login_url="login")
@validate_cart_and_order
def payment(request, cart, order):
    if not cart.has_products() or order.shipping_address is None:
        return redirect("carts:cart")

    billing_profile = order.get_or_set_billing_profile()

    return render(request, "orders/payment.html",{
        "cart":cart,
        "order": order,
        "billing_profile": billing_profile,
        "breadcrumb": breadcrumb(address=True, payment=True),
    })

@login_required(login_url="login")
@validate_cart_and_order
def confirm(request, cart, order):
    if not cart.has_products() or order.shipping_address is None or order.billing_profile is None:
        return redirect("carts:cart")

    shipping_address = order.shipping_address
    
    if shipping_address is None:
        return redirect("orders:address")
    return render(request, "orders/confirm.html", {
        "cart":cart,
        "order":order,
        "breadcrumb":breadcrumb(address=True,payment=True, confirmation=True),
        "shipping_address":shipping_address,
    })

@login_required(login_url="login")
@validate_cart_and_order
def cancel(request,cart, order):
    
    if request.user.id != order.user_id:
        return redirect("carts:cart")

    order.cancel()

    destroy_cart(request)
    destroy_order(request)

    messages.error(request, "ordern cancelada")
    return redirect("index")

@login_required(login_url="login")
@validate_cart_and_order
def complete(request, cart, order):

    if request.user.id != order.user_id:
        return redirect("carts:cart")

    charge = Charge.objects.create_charge(order)
    if charge:
        order.complete()
        thread = threading.Thread(target=Mail.send_complete_order, args=(
            order, request.user
        ))#target = metodo que se va ejecutar en segundo plano, args = argumentos del metodo 
        thread.start()#iniciar el thread
        destroy_cart(request)
        destroy_order(request)

        messages.success(request, "compra completada exitosamente")

    return redirect("index")

juan_store/orders/templates/orders/address.html
{% extends "base.html"%}

<title>Direccion</title>

{% block breadcrumb %}
    {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content%}
    <div class="col">
        {% if shipping_addresses %}
            <div class="h3">
                Recoge el pedido en el punto de entrega
            </div>
            <div class="">
                {% include 'shipping_addresses/snippets/shipping_address.html'%}
                <div class="mt-2">
                    <a href="{% url 'orders:payment'%}" class="btn btn-warning"> Entregar a esta direccion</a>
                </div>
                {% if can_choose_address %}
                    <div class="mt-2">
                        <a href="{% url 'orders:select_address' %}">Otra direccion</a>
                    </div>
                {% endif %}
            </div>
        {% else %}
            <div class="h3">
                Registra tu direccion den envio
            </div>
            <div class="">
                {% url 'orders:address' as next_url%}
                <a href="{% url 'shipping_addresses:create'%}?next={{ next_url }}"> Nueva direccion de envio</a>
            </div>
        {% endif%}
    </div>
{% endblock %}

juan_store/orders/templates/orders/confirm.html
{% extends 'base.html'%}
<title>Confirmar direccion</title>

{% block breadcrumb %}
    {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content%}
    <div class="col-8">
        <div class="h3">
            Confirma tu pedido
        </div>
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-4">
                        <div class="font-weight-bold">
                            Direccion de envio
                        </div>
                        <div class="cart-text">
                            <span>Lugar:</span> {{ shipping_address.address }}
                        </div>
                        <div class="cart-text">
                            <span>Direccion:</span> {{ shipping_address.line1 }}
                        </div>
                        <div class="cart-text">
                            <span>Descripcion:</span> {{ shipping_address.reference }}
                        </div>
                        <div class="cart-text">
                            <span>Codigo postal:</span> {{ shipping_address.postal_code }}
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="font-weight-bold">
                           <span>Metodo de pago</span> 
                        </div>
                        <div class="card-text">
                            <span>Tarjeta terminacion: {{order.billing_profile.last4}}</span>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="font-weigth-bold">
                            <span>Codigo promocional</span>
                        </div>
                        <form id="promocode-form" action="{% url 'promo_codes:validate'%}">
                            <input type="text" name="code" value="{{ order.promo_code.code }}" class="form-control" placeholder="Codigo promocional" {% if order.promo_code %} readonly {%endif%}>
                        </form>
                        <div class="text-success" id="promocode-sucess" style="font-size:14px">
                            {% if order.promo_code %}
                                Codigo aplicado exitosamente
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mt-3">
            <div class="card">
                <div class="card-header">
                    {%if cart.productos.all.count > 1%}
                    <div class="mb-2">
                        <h2><span class="fas fa-list"></span> Productos</h2>
                    </div>
                    {%else%}
                    <div class="mb-2">
                        <h2><span class="fas fa-list"></span> Producto</h2>
                    </div>
                    {%endif%}
                </div>
                <div class="card-body">
                    {%for producto in cart.productos.all%}
                        {% include 'orders/snippets/producto.html' %}
                    {%endfor%}
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        {% url 'orders:complete' as next_url%}
        {% include "orders/snippets/resume.html" with next_url=next_url %}
        <div class="mt-2">
            <a href="{% url 'orders:cancel'%}" class="btn btn-danger"> Cancelar orden</a>
        </div>
    </div>
{%endblock%}

{% block javascript %}
    <script>
        const form = document.getElementById("promocode-form")

        form.addEventListener("submit", function(e){
            e.preventDefault()//prevenimos que haga el submit

            const input = this.code
            const code = input.value
            const url = this.action + "?code=" + code
            const div_total = document.getElementById("order-total")
            const div_success = document.getElementById("promocode-sucess")
            fetch(url)
                .then(response => response.json())
                .then(response => {
                   if(response.status === true){
                    //success
                    div_total.innerHTML = "$" + response.total

                    div_success.classList.remove("text-danger")
                    div_success.classList.add("text-success")

                    div_success.innerHTML = "Codigo aplicado exitosamente"

                    input.readOnly = true
                   }else{
                        div_success.innerHTML = "Codigo no valido"
                        div_success.classList.remove("text-success")
                        div_success.classList.add("text-danger")
                   }
                })
        })
    </script>
{% endblock %}

juan_store/orders/templates/orders/order.html
{% extends 'base.html' %}
<title>Orden</title>
{% block breadcrumb %}
    {% include 'orders/snippets/breadcrumb.html'%}
{% endblock %}
{% block content %}
<div class="col-8">
    <div class="h3">
        Revisa tu pedido
    </div>
    <div class="card">
        <div class="card-body">
            {%for producto in cart.productos.all%}
                {% include 'orders/snippets/producto.html'%}
            {%endfor%}
        </div>
    </div>
</div>
<div class="col">
    {% url 'orders:address' as next_url%}
    {% include 'orders/snippets/resume.html' with next_url=next_url %}
</div>
{%endblock%}

juan_store/orders/templates/orders/orders.html
{% extends "base.html"%}

{% block content%}
    <div class="col">
        <div class="h3">
            Mis pedidos
        </div>
        <div class="">
            {% for order in object_list%}
                {% include "orders/snippets/order.html"%}
            {%endfor%}
        </div>
    </div>
{% endblock%}

juan_store/orders/templates/orders/payment.html
{% extends 'base.html'%}

{% block breadcrumb %}
    {% include 'orders/snippets/breadcrumb.html'%}
{% endblock%}

{% block content %}
<div class="col">
    <div class="h3">
        Metodo de pago
    </div>
    <div>
        {% include 'billing_profiles/snippets/billing_profile.html'%}
    </div>
    <div class="mt-3">
        <a href="{% url 'orders:confirm'%}" class="btn btn-warning">Confirmar</a>
    </div>
</div>
{% endblock%}

juan_store/orders/templates/orders/select_address.html
{% extends 'base.html'%}
<title>Seleccionar direccion</title>
{% block breadcrumb %}
    {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content%}
    <div class="col">
        <div class="h3">
            Selecciona una direccion de envio
        </div>
        <div class="mt-2">
            {% for shipping_address in shipping_addresses %}
                <div class="card mb-2">
                    <div class="card-body">
                        <h5 class="card-title">{{ shipping_address.address}}</h5>
                        <p class="card-title"> {{ shipping_address.postal_code}}</p>
                        <a href="{% url 'orders:check_address' shipping_address.pk%}" class="btn btn-warning">Selecciona direccion</a>
                    </div>
                </div>
            {%endfor%}
        </div>
    </div>
{% endblock %}